# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_book', models.CharField(max_length=60)),
                ('description', models.TextField(blank=b'true')),
                ('ISBN', models.CharField(blank=b'true', max_length=20)),
                ('publishing_house', models.CharField(blank=b'true', max_length=20)),
                ('year', models.IntegerField(blank=b'true')),
                ('quantity', models.IntegerField(blank=b'true')),
            ],
        ),
        migrations.CreateModel(
            name='BooksAuthors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Authors')),
                ('id_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Books')),
            ],
        ),
        migrations.CreateModel(
            name='BooksTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Books')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='bookstags',
            name='id_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Tags'),
        ),
    ]
